### ISSUE TITLE
Redudant args in BCPy

### ISSUE THREAD

**Issue by mzechmeister** [shbhuk/barycorrpy#12]
The keywords `lat`, `longi`, and `alt` are not used in `BCPy` and therefore redundant. Can be removed in favor of `loc`.
I would also rename `longi` to `lon` in `get_BC_vel`.

**Comment by shbhuk** [comment]
Hi @mzechmeister ,
Thanks for the suggestions. I shall work on these, and also your pull request. Can include these v0.2, would also have the UTC2BJD converter included by then.

**Comment by shbhuk** [comment]
Fixed in commit -  a93f3f979ee47c18183f8ab926957dddd72e7476
