### ISSUE TITLE
Astroquery version

### ISSUE THREAD

**Issue by arpita308** [shbhuk/barycorrpy#28]
ERROR: Could not find a version that satisfies the requirement astroquery>0.3.10 (from barycorrpy==0.3)

There is no version > 0.3.10 so it is giving an error. Should it be >= 0.3.10?

**Comment by shbhuk** [comment]
Hi Arpita, you're correct. It should read >=0.3.10. There is a 0.4 which is greater than 0.3.10, but that is still in .dev stage.

**Comment by shbhuk** [comment]
Fixed in https://github.com/shbhuk/barycorrpy/commit/51ec855503b9d9d71b61d63cf3ec7d97a8dbed89
