### ISSUE TITLE
setup.py needs to have barycorrpy.tests

### ISSUE THREAD

**Issue by indiajoe** [shbhuk/barycorrpy#29]
Currently the module barrycorrpy.tests is missing in the setup.py file.
This has to be added to the packages list.

`packages=['barycorrpy','barycorrpy.tests'],`

Otherwise, pip will not install the sub module while package is installed directly. This will result in a `ModuleNotFoundError: No module named 'barycorrpy.tests'`  error while trying to import barrycorpy.

**Comment by shbhuk** [comment]
Hi Joe, might that be because the latest version on pip is 0.2.2.1, whereas the unit tests were added in 0.2.3?

**Comment by indiajoe** [comment]
Yes, we ran into this problem when we tried to install the latest version from github directly.

**Comment by shbhuk** [comment]
Try now.. 
https://github.com/shbhuk/barycorrpy/commit/eed5e3604220e31b3e94b70e046a2c7b7a26e710
