### ISSUE TITLE
erfa not installed

### ISSUE THREAD

**Issue by bjfultn** [shbhuk/barycorrpy#47]
For versions later than 0.4.1 I'm seeing a `ModuleNotFoundError: No module named 'erfa'` when trying to import barycorrpy. I don't see this new requirement listed in setup.py. Is this by design or just an oversight?

**Comment by shbhuk** [comment]
Hi @bjfultn , just checking this right now. 
We just released a new version of barycorrpy (0.4.2 and 0.4.3) to address the astropy erfa deprecation.

**Comment by bjfultn** [comment]
3.6.14 Is `erfa` supposed to be built-in?

**Comment by shbhuk** [comment]
This is a bug, I'll issue a patch shortly.

**Comment by bjfultn** [comment]
Would you like me to Dockerize and setup continuous integration so that kind of requirement bug is automatically caught in the future?

**Comment by shbhuk** [comment]
That would be great, thanks!
Meanwhile I've issued a bug fix in `v0.4.4`, and pushed it to the Master branch. Will push it PyPI shortly.

**Comment by shbhuk** [comment]
I've pushed `v0.4.4` to PyPI. 
@bjfultn - thank you for working on the CI, and let me know if you need any help for that.
