### ISSUE TITLE
Implement UTC_BJD converter as additional feature.

### ISSUE THREAD

**Issue by shbhuk** [shbhuk/barycorrpy#5]
Since all the framework is already in place include the UTC to BJD converter.

**Comment by mzechmeister** [comment]
Astropy has now a converter:
http://docs.astropy.org/en/stable/time/#barycentric-and-heliocentric-light-travel-time-corrections
Just a few lines. So easy to implement. I tried it and it works after I worked around one problem
https://github.com/astropy/astropy/issues/7051#issuecomment-356861381

**Comment by shbhuk** [comment]
The problem with this would be the same one that we are facing with the astropy time converter from UTC to TDB, namely the leap seconds 
https://github.com/astropy/astropy/pull/6861

**Comment by shbhuk** [comment]
Added in devel, will be added in v2
